language: cpp
compiler:
  - gcc
before_script:
  - travis_retry ./bootstrap.sh
  - travis_retry ./configure
notifications:
  recipients:
    - milan.dunghubel@gmail.com
  email:
    on_success: change
    on_failure: always
env:
  - LANG="en_US.UTF-8"
os:
  - linux
  - osx
